# Generated by Django 5.1.6 on 2025-03-08 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_storing_app', '0002_aicte_files'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Aicte_files',
        ),
    ]
