# Generated by Django 5.1.6 on 2025-03-08 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_storing_app', '0003_delete_aicte_files'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aicte_files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('pdf_file', models.FileField(upload_to='aicte_files/')),
                ('published_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
