# Generated by Django 5.1.6 on 2025-03-12 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_storing_app', '0005_organizationchart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrganizationChart',
        ),
    ]
