# Generated by Django 5.1.6 on 2025-03-12 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_storing_app', '0006_delete_organizationchart'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationChart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=225)),
                ('pdf_file', models.FileField(upload_to='organization_chart/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
