# Generated by Django 5.1.6 on 2025-03-02 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('duration', models.CharField(max_length=200)),
                ('entry_qualification', models.CharField(max_length=500)),
                ('intake', models.IntegerField()),
                ('program_pattern', models.CharField(max_length=500)),
                ('theory_practical_ratio', models.CharField(max_length=100)),
                ('ecology_environment', models.CharField(max_length=500)),
                ('entrepreneurship_development', models.CharField(max_length=500)),
                ('industrial_exposure', models.CharField(max_length=500)),
                ('discipline', models.CharField(max_length=200)),
            ],
        ),
    ]
