# Generated by Django 5.1.6 on 2025-03-02 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college_web_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(max_length=10)),
                ('enrolled_students', models.PositiveIntegerField()),
                ('passed_students', models.PositiveIntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='college_web_app.courses')),
            ],
        ),
    ]
