# Generated by Django 5.1.6 on 2025-03-02 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college_web_app', '0003_galleryimages'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlacementRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(choices=[(2000, '2000'), (2001, '2001'), (2002, '2002'), (2003, '2003'), (2004, '2004'), (2005, '2005'), (2006, '2006'), (2007, '2007'), (2008, '2008'), (2009, '2009'), (2010, '2010'), (2011, '2011'), (2012, '2012'), (2013, '2013'), (2014, '2014'), (2015, '2015'), (2016, '2016'), (2017, '2017'), (2018, '2018'), (2019, '2019'), (2020, '2020'), (2021, '2021'), (2022, '2022'), (2023, '2023'), (2024, '2024'), (2025, '2025'), (2026, '2026'), (2027, '2027'), (2028, '2028'), (2029, '2029'), (2030, '2030')], default=2024)),
                ('candidate_name', models.CharField(max_length=255)),
                ('branch', models.CharField(max_length=50)),
                ('company_name', models.CharField(max_length=255)),
                ('package', models.FloatField(help_text='Package in Lakh per Annum')),
            ],
        ),
    ]
