# Generated by Django 5.1.6 on 2025-03-02 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college_web_app', '0004_placementrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placementrecord',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placements', to='college_web_app.courses'),
        ),
    ]
