# Generated by Django 5.1.6 on 2025-03-02 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college_web_app', '0005_alter_placementrecord_branch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placementrecord',
            name='branch',
        ),
        migrations.AddField(
            model_name='placementrecord',
            name='branch_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='college_web_app.courses'),
        ),
    ]
