# Generated by Django 5.1.6 on 2025-03-02 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college_web_app', '0006_remove_placementrecord_branch_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placementrecord',
            name='branch_fk',
        ),
        migrations.AddField(
            model_name='placementrecord',
            name='branch',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
