# Generated by Django 5.1.6 on 2025-03-06 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college_web_app', '0007_remove_placementrecord_branch_fk_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('designation', models.CharField(max_length=255)),
                ('qualification', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='staff_images/')),
            ],
        ),
    ]
