# Generated by Django 5.1.6 on 2025-03-07 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college_web_app', '0012_carouselimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(max_length=10)),
                ('department', models.CharField(max_length=100)),
                ('semester_year', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('marks_obtained', models.CharField(max_length=20)),
                ('percentage', models.FloatField()),
            ],
        ),
    ]
