# Generated by Django 5.1.6 on 2025-03-07 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college_web_app', '0013_topper'),
    ]

    operations = [
        migrations.AddField(
            model_name='topper',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='toppers', to='college_web_app.courses'),
        ),
        migrations.AlterField(
            model_name='topper',
            name='department',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='topper',
            name='marks_obtained',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='topper',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='topper',
            name='semester_year',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='topper',
            name='session',
            field=models.CharField(max_length=20),
        ),
    ]
