# Generated by Django 5.1.6 on 2025-03-07 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('college_web_app', '0014_topper_course_alter_topper_department_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topper',
            name='department',
        ),
    ]
