# Generated by Django 5.1.6 on 2025-03-07 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('college_web_app', '0015_remove_topper_department'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topper',
            old_name='semester_year',
            new_name='year',
        ),
    ]
