# Generated by Django 5.1.6 on 2025-03-07 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('college_web_app', '0016_rename_semester_year_topper_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topper',
            name='session',
        ),
    ]
