# Generated by Django 5.1.6 on 2025-03-07 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('college_web_app', '0017_remove_topper_session'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseresult',
            name='course',
        ),
        migrations.RemoveField(
            model_name='topper',
            name='course',
        ),
        migrations.DeleteModel(
            name='PlacementRecord',
        ),
        migrations.DeleteModel(
            name='CourseResult',
        ),
        migrations.DeleteModel(
            name='Courses',
        ),
        migrations.DeleteModel(
            name='Topper',
        ),
    ]
