# Generated by Django 5.1.6 on 2025-03-09 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('college_web_app', '0020_section'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Section',
        ),
    ]
