# Generated by Django 5.1.6 on 2025-03-11 04:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college_web_app', '0022_section'),
        ('student_app', '0010_subject_previouspaper'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contact_no', models.CharField(max_length=15)),
                ('passing_year', models.PositiveIntegerField()),
                ('company', models.CharField(blank=True, max_length=200, null=True)),
                ('work_address', models.CharField(blank=True, max_length=300, null=True)),
                ('designation', models.CharField(blank=True, max_length=100, null=True)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alumni', to='student_app.courses')),
            ],
        ),
    ]
