# Generated by Django 5.1.6 on 2025-03-12 15:01

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college_web_app', '0024_contactus'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollegeContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('content', tinymce.models.HTMLField()),
            ],
        ),
    ]
