# Generated by Django 5.1.6 on 2025-03-12 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('college_web_app', '0025_collegecontent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CollegeContent',
        ),
    ]
