# Generated by Django 5.1.6 on 2025-03-12 15:08

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college_web_app', '0026_delete_collegecontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollegeContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(choices=[('message', 'Message'), ('about', 'About GP Kotdwara')], max_length=10, unique=True)),
                ('content', tinymce.models.HTMLField()),
            ],
        ),
    ]
