# Generated by Django 5.1.6 on 2025-03-07 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('duration', models.CharField(max_length=200)),
                ('entry_qualification', models.CharField(max_length=500)),
                ('intake', models.IntegerField()),
                ('program_pattern', models.CharField(max_length=500)),
                ('theory_practical_ratio', models.CharField(max_length=100)),
                ('ecology_environment', models.CharField(max_length=500)),
                ('entrepreneurship_development', models.CharField(max_length=500)),
                ('industrial_exposure', models.CharField(max_length=500)),
                ('discipline', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PlacementRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(choices=[(2000, '2000'), (2001, '2001'), (2002, '2002'), (2003, '2003'), (2004, '2004'), (2005, '2005'), (2006, '2006'), (2007, '2007'), (2008, '2008'), (2009, '2009'), (2010, '2010'), (2011, '2011'), (2012, '2012'), (2013, '2013'), (2014, '2014'), (2015, '2015'), (2016, '2016'), (2017, '2017'), (2018, '2018'), (2019, '2019'), (2020, '2020'), (2021, '2021'), (2022, '2022'), (2023, '2023'), (2024, '2024'), (2025, '2025'), (2026, '2026'), (2027, '2027'), (2028, '2028'), (2029, '2029'), (2030, '2030')], default=2024)),
                ('candidate_name', models.CharField(max_length=255)),
                ('branch', models.CharField(max_length=50)),
                ('company_name', models.CharField(max_length=255)),
                ('package', models.FloatField(help_text='Package in Lakh per Annum')),
            ],
        ),
        migrations.CreateModel(
            name='CourseResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(max_length=10)),
                ('enrolled_students', models.PositiveIntegerField()),
                ('passed_students', models.PositiveIntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='student_app.courses')),
            ],
        ),
        migrations.CreateModel(
            name='Topper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('year', models.CharField(max_length=20)),
                ('marks_obtained', models.CharField(max_length=50)),
                ('percentage', models.FloatField()),
                ('course', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='toppers', to='student_app.courses')),
            ],
        ),
    ]
