# Generated by Django 5.1.6 on 2025-03-09 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0008_previouspaper'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PreviousPaper',
        ),
    ]
