# Generated by Django 5.1.6 on 2025-03-12 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0011_facility'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationChart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=225)),
                ('organization_chart_file', models.FileField(upload_to='org_chart_file/')),
            ],
        ),
    ]
