# Generated by Django 5.1.6 on 2025-03-12 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0012_organizationchart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrganizationChart',
        ),
    ]
